__version__ = '0.3.0'

DINGOS_AUTHORING_IMPORTER_REGISTRY = []

DINGOS_AUTHORING_CELERY_BUG_WORKAROUND = False

DINGOS_AUTHORING_DATA_FILESYSTEM_ROOT = None

DINGOS_AUTHORING_DATA_STORAGE = None


DINGOS_AUTHORING_POSTPROCESSOR_TASK = 'mantis_authoring.tasks.export_to_actionables'
